// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsBV4K1Q9ULUVOitlSKiWZGP12sO0i_EM',
    appId: '1:987057244567:web:1ed9179c4a153a94369cd2',
    messagingSenderId: '987057244567',
    projectId: 'codepal-142',
    authDomain: 'codepal-142.firebaseapp.com',
    storageBucket: 'codepal-142.appspot.com',
    measurementId: 'G-3KVQN19WFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhsHFsYjyLlB4fNkA1KFQTJTgtult4H6k',
    appId: '1:987057244567:android:417b8bca56b0e355369cd2',
    messagingSenderId: '987057244567',
    projectId: 'codepal-142',
    storageBucket: 'codepal-142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrI_2Q6FfKfoAmSC3GzwA3nY-PUcBib28',
    appId: '1:987057244567:ios:93fcc285cdec9b6c369cd2',
    messagingSenderId: '987057244567',
    projectId: 'codepal-142',
    storageBucket: 'codepal-142.appspot.com',
    iosBundleId: 'com.example.codepal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrI_2Q6FfKfoAmSC3GzwA3nY-PUcBib28',
    appId: '1:987057244567:ios:68a52a9704d4e662369cd2',
    messagingSenderId: '987057244567',
    projectId: 'codepal-142',
    storageBucket: 'codepal-142.appspot.com',
    iosBundleId: 'com.example.codepal.RunnerTests',
  );
}
